Add vercel blog starter to examples
opennextjs/opennextjs-cloudflare pull request #86
Opened 2024-10-10 17:43 UTC by shashankboosi

Added the vercel blog starter to examples as a way to test applications. I used this from vercel which wasn't working but fixed it to the needs of the adapter

2024-10-10 19:05 UTC, vicb commented on pnpm-lock.yaml
Could you please remove this file.
It should not be there in the monorepo setup.
Thanks!

2024-10-10 19:07 UTC, vicb commented
>  I used this from vercel which wasn't working but fixed it to the needs of the adapter

One thing you can do is two separate commit:
- first commit would be "import blog start at <sha>"
- second commit would be "adapt for cloudflare worker"

It's nice to have the required changes in the history

2024-10-12 02:40 UTC, shashankboosi commented
Made all the recommended changes and had the commits in the flow, that is nice to read

2024-10-12 02:57 UTC, shashankboosi commented
I had to delete the commit where I remove `pnpm-lock` because currently there is no way to run github actions without a lock file and there is an open issue about it [here](https://github.com/actions/setup-node/issues/928).

Maybe if you want, I can investigate it as a separate issue

2024-10-12 07:29 UTC, vicb requested changes
LGTM, thank you so much!

2 things:
- could you please add [a patch changeset](https://github.com/opennextjs/opennextjs-cloudflare/pull/86#issuecomment-2405701734)
- it would be nice to add a basic e2e test, you can check i.e. the API example. If you are willing to do this, you can do it in a follow up PR when you have time. No rush.

2024-10-12 08:13 UTC, shashankboosi commented
@vicb I have added the changeset. In regards to adding an e2e test, I will do it in another PR as I don't want to keep holding this one :)

2024-10-12 09:54 UTC, vicb commented
> I don't want to keep holding this one :)

Yep, makes sense.

Thank for adding the example!

2024-10-12 10:00 UTC, vicb approved these changes

2024-10-12 10:00 UTC, merged